language: python
dist: xenial

python:
  - "3.7"

addons:
  apt:
    update: true

install:
  - pip install -r .travisreqs.txt
  - pip install .
  - python -m pyspedas.mms.tests.setup_tests

script: 
  - python -m pyspedas.mms.tests.load_routine_tests
