language: python
python:
  - "3.5"
  - "3.6"

before_install:
  - sudo apt-get install libqt5x11extras5

install:
  - pip install -r requirements.txt
  - pip install .
  - python -m pyspedas.mms.tests.setup_tests

script: 
  - python -m pyspedas.mms.tests.load_routine_tests
