language: python
dist: xenial

python:
  - "3.7"

addons:
  apt:
    update: true

install:
  - pip install -r requirements.txt
  - pip install coveralls

script: 
  - coverage run -a -m pyspedas.examples.tests.tests
  
after_success:
  - coveralls
