language: python
dist: xenial

python:
  - "3.7"

addons:
  apt:
    update: true

install:
  - pip install -r .travisreqs.txt
  - pip install coveralls
  - python -m pyspedas.mms.tests.setup_tests

script: 
  - coverage run -a -m pyspedas.utilities.tests.run_all_tests

after_success:
  - coveralls --base_dir pyspedas
