language: python
dist: xenial

python:
  - "3.7"

addons:
  apt:
    update: true

install:
  - pip install -r .travisreqs.txt
  - pip install coveralls
  - python -m pyspedas.mms.tests.setup_tests

script: 
  - coverage run -a -m pyspedas.mms.tests.load_routine_tests
  - coverage run -a -m pyspedas.mms.tests.feeps
  - coverage run -a -m pyspedas.mms.tests.eis
  - coverage run -a -m pyspedas.mms.tests.file_filter
  - coverage run -a -m pyspedas.dscovr.tests.tests
  - coverage run -a -m pyspedas.utilities.tests.download_tests
  - coverage run -a -m pyspedas.cluster.tests.tests
  - coverage run -a -m pyspedas.csswe.tests.tests
  - coverage run -a -m pyspedas.ace.tests.tests
  - coverage run -a -m pyspedas.equator_s.tests.tests
  - coverage run -a -m pyspedas.geotail.tests.tests
  - coverage run -a -m pyspedas.image.tests.tests

after_success:
  - coveralls
