language: python
dist: xenial

python:
  - "3.7"

before_install:
  - sudo apt-get update
  - sudo apt-get upgrade
  - sudo apt-get install python-pyqt5

install:
  - pip install -r requirements.txt
  - pip install .
  - python -m pyspedas.mms.tests.setup_tests

script: 
  - python -m pyspedas.mms.tests.load_routine_tests
